// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Prisma Migrate needs a direct (non-pooled) connection to take
    // advisory locks. The app itself connects via the pooled URL at
    // runtime instead (see src/lib/db.ts) — see PRD 8.1 on why pooling
    // is mandatory for Vercel serverless functions.
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],
  },
});
